server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: hamid
    password: hamid
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true