server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: hamid
    password: hamid
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true